import { historyImages } from '../assets/history/historyImages'
import type { TravelHistory } from '../types/history'

export const travelHistories: TravelHistory[] = [
  {
    id: 'history-beijing',
    destination: '北京',
    title: '北京三日游',
    status: '已完成',
    dateRange: '2026.8.10 - 2026.8.12',
    people: 3,
    coverImageUrl: historyImages.beijingCover,
    totalExpenseCny: 2350,
    routeItems: [
      {
        id: 'route-1',
        imageUrl: historyImages.forbiddenCity,
        attractionName: '故宫博物院',
        time: 'Day 1 09:00 - 12:00',
        costCny: 180,
        description: '从午门进入，沿中轴线参观三大殿与珍宝馆，节奏以文化历史讲解为主。',
      },
      {
        id: 'route-2',
        imageUrl: historyImages.jingshan,
        attractionName: '景山公园日落',
        time: 'Day 1 16:30 - 18:30',
        costCny: 6,
        description: '傍晚登高俯瞰故宫屋脊和北京城，作为第一天的轻量收尾。',
      },
      {
        id: 'route-3',
        imageUrl: historyImages.summerPalace,
        attractionName: '颐和园',
        time: 'Day 2 10:00 - 14:00',
        costCny: 120,
        description: '围绕昆明湖和长廊安排慢行路线，减少换乘与重复步行。',
      },
      {
        id: 'route-4',
        imageUrl: historyImages.templeOfHeaven,
        attractionName: '天坛公园',
        time: 'Day 3 09:30 - 11:30',
        costCny: 45,
        description: '清晨游览祈年殿与回音壁，结束后预留返程和午餐时间。',
      },
    ],
    dailyExpenses: [
      { date: '8.10', amountCny: 890 },
      { date: '8.11', amountCny: 930 },
      { date: '8.12', amountCny: 530 },
    ],
    categoryExpenses: [
      { name: '景点/门票', amountCny: 351, color: '#0071EB' },
      { name: '餐饮/美食', amountCny: 920, color: '#FF6F61' },
      { name: '交通/出行', amountCny: 479, color: '#10B981' },
      { name: '住宿/酒店', amountCny: 600, color: '#F59E0B' },
    ],
    expenseDetails: [
      { id: 'expense-1', date: '8.10', title: '故宫门票与讲解', category: '景点/门票', amountCny: 180 },
      { id: 'expense-2', date: '8.10', title: '胡同晚餐', category: '餐饮/美食', amountCny: 360 },
      { id: 'expense-3', date: '8.11', title: '酒店住宿', category: '住宿/酒店', amountCny: 600 },
      { id: 'expense-4', date: '8.11', title: '地铁与打车', category: '交通/出行', amountCny: 179 },
      { id: 'expense-5', date: '8.12', title: '天坛门票', category: '景点/门票', amountCny: 45 },
    ],
  },
  {
    id: 'history-chengdu',
    destination: '成都',
    title: '成都美食周末',
    status: '已完成',
    dateRange: '2026.7.18 - 2026.7.20',
    people: 2,
    coverImageUrl: historyImages.chengduCover,
    totalExpenseCny: 1680,
    routeItems: [],
    dailyExpenses: [],
    categoryExpenses: [],
    expenseDetails: [],
  },
  {
    id: 'history-shanghai',
    destination: '上海',
    title: '上海亲子两日',
    status: '进行中',
    dateRange: '2026.6.6 - 2026.6.7',
    people: 4,
    coverImageUrl: historyImages.shanghaiCover,
    totalExpenseCny: 3120,
    routeItems: [],
    dailyExpenses: [],
    categoryExpenses: [],
    expenseDetails: [],
  },
  {
    id: 'history-xian',
    destination: '西安',
    title: '西安历史路线',
    status: '已归档',
    dateRange: '2026.5.1 - 2026.5.4',
    people: 3,
    coverImageUrl: historyImages.xianCover,
    totalExpenseCny: 2760,
    routeItems: [],
    dailyExpenses: [],
    categoryExpenses: [],
    expenseDetails: [],
  },
]
